#!/bin/bash
if [[ $# -gt 1 ]]; then
  echo "Too much arguments."
  exit 1
fi

if [[ $# -eq 1 ]]; then
  file_name=$1
  if [[ ! -f $file_name ]]; then
    echo "File not found."
    exit 1
  fi
fi

if [[ -t 0 ]]; then # if stdin is filled
  xclip -selection clipoard -o
else
  read stdin
  echo "$stdin" | xclip -selection clipboard
  echo piped stdin to clipboard
fi
