#!/bin/sh
set -e
file="/tmp/ocr.png"
# maim --select /tmp/ocr.png
rm -f $file
spectacle --output=$file --background --region
tesseract -l vie+eng /tmp/ocr.png stdout | xclip -selection clipboard
notify-send "OCR (tesseract)" "Copied text to clipboard"
# Dependencies (arch)
# tesseract
# tesseract-data-vie
# tesseract-data-eng
