#!/bin/bash

flameshot gui --raw | tesseract -l eng+vie stdin stdout | xclip -selection clipboard

if [[ $? -ne 0 ]]; then
  echo "Some went wrong. Failed to capture and convert to text."
  exit 1
else
  echo "Success."
  notify-send "OCR" "Converted image to text, copied text to clipboard."
fi
