#!/usr/bin/env python
from datetime import datetime
from dateutil import parser
from time import sleep
import sys

argv_str = "".join(sys.argv[1:])
until = parser.parse(argv_str)
now = datetime.now()
if (diff := until - now).total_seconds() < 0:
    print("Can't sleep negative amount of time")
else:
    sleep(diff.total_seconds())
