#!/usr/bin/bash
deps vlc pamixer dwm-notify

set -e
function volume_info {
  volume=$(pamixer --get-volume)
  muted=$(pamixer --get-mute)
  if [[ $muted = true ]]; then
    echo muted
    return 0
  fi
  echo $volume
}

if [[ $# -eq 0 ]]; then
  volume_info
  exit 0
fi

action=$1
case $action in
  "up")
    pamixer --increase 5 --allow-boost
    volume_info
    ;;
  "down")
    pamixer --decrease 5 --allow-boost
    volume_info
    ;;
  "reset")
    pamixer --unmute
    pamixer --set-volume 100
    volume_info
    ;;
  "toggle")
    pamixer --toggle-mute
    volume_info
    ;;
esac

if [[ $(pamixer --get-mute) = true ]]; then
  dunstify -a progress_bar_blocked -t 1000 -h string:x-dunst-stack-tag:volume -h int:value:"$(pamixer --get-volume)" "Volume"
else
  dunstify -a progress_bar -t 1000 -h string:x-dunst-stack-tag:volume -h int:value:"$(pamixer --get-volume)" "Volume"
fi
